name: Main test
on: [push]
jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Python installation
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Dependencies installation
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Create .env file
      run: |
        echo "POSTGRES_HOST=localhost" >> .env
        echo "POSTGRES_PORT=7648" >> .env
        echo "POSTGRES_USER=sirius_2024" >> .env
        echo "POSTGRES_PASSWORD=change_me" >> .env
        echo "POSTGRES_DB=postgres" >> .env
        echo "TESTING=True" >> .env
    - name: Flake8
      run: |
        flake8 

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Python installation
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Dependencies installation
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create .env file
      run: |
        echo "POSTGRES_HOST=localhost" >> .env
        echo "POSTGRES_PORT=7648" >> .env
        echo "POSTGRES_USER=sirius_2024" >> .env
        echo "POSTGRES_PASSWORD=change_me" >> .env
        echo "POSTGRES_DB=postgres" >> .env
        echo "TESTING=True" >> .env
    - name: Pytest
      run: |
        pytest .